"""Unit tests for the GREIS rotate-left-2/XOR checksum.

Expected values are hand-traced from the documented algorithm (not
generated by calling this module's own code), so these catch a
transcription error in the rotate/XOR arithmetic itself:

  compute_checksum(b'\\x00'):       res=0; rot(0)^0=0;       final=rot(0)=0
  compute_checksum(b'\\x01'):       res=0; rot(0)^1=1;       final=rot(1)=4
  compute_checksum(b'\\xC0'):       res=0; rot(0)^192=192;   final=rot(192)=3
  compute_checksum(b'\\x01\\x02'):  res=0; rot(0)^1=1; rot(1)^2=4^2=6;
                                    final=rot(6)=24
"""

from __future__ import annotations

from greis.checksum import compute_checksum, verify_checksum


def test_checksum_of_single_zero_byte_is_zero():
    assert compute_checksum(b"\x00") == 0


def test_checksum_of_single_one_byte():
    assert compute_checksum(b"\x01") == 4


def test_checksum_with_wraparound_bits():
    assert compute_checksum(b"\xc0") == 3


def test_checksum_of_two_bytes():
    assert compute_checksum(b"\x01\x02") == 24


def test_verify_checksum_true_for_matching_value():
    assert verify_checksum(b"\x01\x02", 24) is True


def test_verify_checksum_false_for_mismatched_value():
    assert verify_checksum(b"\x01\x02", 0) is False
